# melos_managed_dependency_overrides: api,auth,component_library,domain,feature_auth,feature_detail,feature_home,key_value_storage,list_cache
dependency_overrides:
  api:
    path: ../api
  auth:
    path: ../../services/auth
  component_library:
    path: ../component_library
  domain:
    path: ../../domain
  feature_auth:
    path: ../../features/feature_auth
  feature_detail:
    path: ../../features/feature_detail
  feature_home:
    path: ../../features/feature_home
  key_value_storage:
    path: ../key_value_storage
  list_cache:
    path: ../list_cache
