targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/src/models/**
          exclude:
            - lib/src/api/**
      retrofit_generator:
        generate_for:
          include:
            - lib/src/api/**
          exclude:
            - lib/src/models/**
      json_serializable:
        generate_for:
          include:
            - lib/src/models/**
          exclude:
            - lib/src/api/**
