/// SharedPreferences storage key enum
enum PreferenceKey {
  agreePrivacyAndProtocol('agree_privacy_and_protocol'),
  agreePrivacyDriverLicense('agree_privacy_driver_license'),
  agreeLocationDeviceAgreement('agree_location_device_agreement'),
  firstLaunchOnboardingCompleted('first_launch_onboarding_completed'),
  loginByUserName('login_by_user_name'),
  loginByWeChat('login_by_we_chat'),
  registerByUserName('register_by_user_name'),
  locationCityName('location_city_name'),
  locationCityCode('location_city_code'),
  locationFocusDeviceId('mine_location_focus_device_id'),
  locationSelectedDeviceIds('mine_location_selected_device_ids'),
  locationIsExpand('mine_location_is_expand'),
  locationIsLine('mine_location_is_line'),
  tripInfoSelectedCarIds('trip_info_car_ids'),
  tripInfoSelectedDate('trip_info_date'),
  tripStatisticSelectedCarIds('trip_statistic_car_ids'),
  tripStatisticSelectedDate('trip_statistic_date'),
  tripStatisticSelectedYear('trip_statistic_year'),
  tripStatisticSelectedMonth('trip_statistic_month'),
  tripStatisticSelectedYearOrMonth('trip_statistic_year_or_month'),
  tripStatisticSelectedYearMonth('trip_statistic_year_month'),
  fenceStatisticSelectedYear('fence_statistic_selected_year'),
  fenceStatisticSelectedYearMonth('fence_statistic_year_month'),
  fenceStatisticSelectedMonth('fence_statistic_selected_month'),
  fenceStatisticIsMonth('fence_statistic_is_month'),
  fenceStatisticSelectedYearOrMonth('fence_statistic_year_or_month'),
  fenceRecordSelectedCarIds('fence_record_car_ids'),
  fenceRecordSelectedDate('fence_record_date'),
  fenceRecordFenceIds('fence_record_fence_id'),
  incomeExpenseStatisticSelectedCarIds('income_expense_statistic_car_ids'),
  incomeExpenseStatisticSelectedYear('income_expense_statistic_year'),
  energyConsumptionStatisticSelectedCarIds('energy_consumption_statistic_car_ids'),
  energyConsumptionStatisticSelectedDate('energy_consumption_statistic_date'),
  circleIntro('circle_intro'),
  rectangleIntro('rectangle_intro'),
  polygonIntro('polygon_intro'),
  carEventInputLimit('car_event_input_limit'),
  smallCarSpeedSegmentConfig('small_car_speed_segment_config'),
  truckSpeedSegmentConfig('truck_speed_segment_config'),
  motorcycleSpeedSegmentConfig('motorcycle_speed_segment_config'),
  electricCarSpeedSegmentConfig('electric_car_speed_segment_config'),
  otherSpeedSegmentConfig('other_speed_segment_config'),
  adConfigVersion('ad_config_version'),
  reminderSelectedCarIds('reminder_car_ids'),
  reminderSelectedStatusIds('reminder_status_ids'),
  reminderSelectedDate('reminder_date'),
  reminderSelectedStatus('reminder_status'),
  carListDataMode('car_list_data_mode'),
  ;

  final String rawKey;
  const PreferenceKey(this.rawKey);
}
